ALTER TABLE users ADD COLUMN password_hash text;
ALTER TABLE users ADD COLUMN email_verified boolean NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN disabled boolean NOT NULL DEFAULT false;
CREATE UNIQUE INDEX users_email_lower ON users(lower(email));
CREATE TABLE sessions (id_hash text PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), csrf_token text NOT NULL, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX sessions_user ON sessions(user_id);
CREATE TABLE account_tokens (token_hash text PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), kind text NOT NULL CHECK(kind IN ('verify','reset')), expires_at timestamptz NOT NULL);
CREATE TABLE auth_attempts (key text PRIMARY KEY, count int NOT NULL, resets_at timestamptz NOT NULL);
ALTER TABLE items ADD COLUMN status text NOT NULL DEFAULT 'available' CHECK(status IN ('offered','available','exhausted','disposed'));
ALTER TABLE items ADD COLUMN weight_grams int NOT NULL DEFAULT 0 CHECK(weight_grams >= 0);
ALTER TABLE items ADD COLUMN category text NOT NULL DEFAULT 'other';
ALTER TABLE items ADD COLUMN allergens text[] NOT NULL DEFAULT '{}';
ALTER TABLE items ADD COLUMN handling_notes text NOT NULL DEFAULT '';
ALTER TABLE items ADD COLUMN created_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE items ADD CONSTRAINT items_price_nonnegative CHECK(price_cents IS NULL OR price_cents >= 0) NOT VALID;
ALTER TABLE donations ADD COLUMN received_at timestamptz;
ALTER TABLE donations ADD COLUMN notes text NOT NULL DEFAULT '';
ALTER TABLE donation_items ADD COLUMN offered_qty int;
ALTER TABLE donation_items ADD COLUMN received_qty int NOT NULL DEFAULT 0;
ALTER TABLE donation_items ADD COLUMN name_snapshot text;
ALTER TABLE donation_items ADD COLUMN unit_snapshot text;
UPDATE donation_items di SET offered_qty=i.qty, name_snapshot=i.name, unit_snapshot=i.unit FROM items i WHERE i.id=di.item_id;
UPDATE donation_items di SET received_qty=di.offered_qty FROM donations d WHERE d.id=di.donation_id AND d.status IN ('received','distributed');
ALTER TABLE donation_items ALTER COLUMN offered_qty SET NOT NULL;
ALTER TABLE donation_items ADD CONSTRAINT donation_qty_positive CHECK(offered_qty > 0) NOT VALID;
UPDATE items SET status='offered',qty=0 WHERE id IN (SELECT di.item_id FROM donation_items di JOIN donations d ON d.id=di.donation_id WHERE d.status='scheduled');
ALTER TABLE events ADD COLUMN starts_at timestamptz;
ALTER TABLE events ADD COLUMN ends_at timestamptz;
ALTER TABLE events ADD COLUMN cutoff_at timestamptz;
ALTER TABLE events ADD COLUMN timezone text NOT NULL DEFAULT 'Europe/Berlin';
ALTER TABLE events ADD COLUMN capacity int NOT NULL DEFAULT 100 CHECK(capacity > 0);
ALTER TABLE events ADD COLUMN status text NOT NULL DEFAULT 'scheduled' CHECK(status IN ('scheduled','cancelled','completed'));
UPDATE events SET starts_at=date,ends_at=date+interval '3 hours',cutoff_at=date;
ALTER TABLE events ALTER COLUMN starts_at SET NOT NULL;
ALTER TABLE events ALTER COLUMN ends_at SET NOT NULL;
ALTER TABLE events ALTER COLUMN cutoff_at SET NOT NULL;
ALTER TABLE orders DROP CONSTRAINT orders_status_check;
ALTER TABLE orders ADD CONSTRAINT orders_status_check CHECK(status IN ('pending','confirmed','picked-up','delivered','cancelled','expired'));
ALTER TABLE orders ADD COLUMN payment_status text NOT NULL DEFAULT 'not-required' CHECK(payment_status IN ('not-required','pending','paid','failed','refunded','refund-pending'));
ALTER TABLE orders ADD COLUMN pickup_token text UNIQUE;
ALTER TABLE orders ADD COLUMN fulfillment text NOT NULL DEFAULT 'pickup' CHECK(fulfillment IN ('pickup','delivery'));
ALTER TABLE orders ADD COLUMN delivery_address text;
ALTER TABLE orders ADD COLUMN assigned_volunteer_id uuid REFERENCES users(id);
ALTER TABLE orders ADD COLUMN delivery_proof text;
ALTER TABLE orders ADD COLUMN completed_at timestamptz;
ALTER TABLE orders ADD COLUMN expires_at timestamptz;
ALTER TABLE orders ADD COLUMN stripe_session_id text UNIQUE;
ALTER TABLE orders ADD COLUMN stripe_payment_intent text;
ALTER TABLE orders ADD COLUMN checkout_url text;
ALTER TABLE orders ADD COLUMN reminder_sent boolean NOT NULL DEFAULT false;
ALTER TABLE orders ADD CONSTRAINT orders_money_positive CHECK(coalesce(total_cents,0)>=0 AND coalesce(support_contribution_cents,0)>=0) NOT VALID;
ALTER TABLE order_items ADD COLUMN name_snapshot text;
ALTER TABLE order_items ADD COLUMN unit_snapshot text;
ALTER TABLE order_items ADD COLUMN price_cents int NOT NULL DEFAULT 0 CHECK(price_cents>=0);
ALTER TABLE order_items ADD COLUMN weight_grams int NOT NULL DEFAULT 0 CHECK(weight_grams>=0);
UPDATE order_items oi SET name_snapshot=i.name,unit_snapshot=i.unit,price_cents=greatest(coalesce(i.price_cents,0),0),weight_grams=i.weight_grams FROM items i WHERE i.id=oi.item_id;
CREATE TABLE inventory_movements (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), item_id uuid NOT NULL REFERENCES items(id), delta int NOT NULL, kind text NOT NULL CHECK(kind IN ('opening','receipt','reserve','restock','dispose','expire')), reason text NOT NULL DEFAULT '', actor_id uuid REFERENCES users(id), order_id uuid REFERENCES orders(id), created_at timestamptz NOT NULL DEFAULT now());
INSERT INTO inventory_movements(item_id,delta,kind,reason) SELECT id,qty,'opening','Migrated balance; historical quantities unavailable' FROM items WHERE status<>'offered';
CREATE INDEX inventory_movements_item ON inventory_movements(item_id,created_at);
CREATE TABLE idempotency_keys (user_id uuid NOT NULL REFERENCES users(id), key text NOT NULL, request_hash text NOT NULL, order_id uuid NOT NULL REFERENCES orders(id), created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_id,key));
CREATE TABLE audit_log (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),actor_id uuid REFERENCES users(id), action text NOT NULL,entity_type text NOT NULL,entity_id text,details jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), subject text NOT NULL, body text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(),read_at timestamptz);
CREATE TABLE mail_outbox (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid REFERENCES users(id),recipient text NOT NULL,subject text NOT NULL,body text NOT NULL,status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','sent','failed')),attempts int NOT NULL DEFAULT 0,available_at timestamptz NOT NULL DEFAULT now(),sent_at timestamptz,last_error text,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE stripe_events (id text PRIMARY KEY,type text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE item_images ADD COLUMN content_type text;
ALTER TABLE item_images ADD COLUMN size_bytes int;
CREATE INDEX items_availability ON items(status,is_surplus,expires_on);
CREATE INDEX orders_user ON orders(user_id,created_at);
CREATE INDEX orders_event ON orders(event_id,status);
CREATE INDEX mail_outbox_pending ON mail_outbox(status,available_at);
