import { useState, type FormEvent } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { z } from 'zod'
import { mutation } from '../lib/api'
import { useAuth } from '../lib/auth'
import { useAction, useQuery } from '../lib/hooks'
import { membershipSchema, okSchema } from '../lib/schemas'
import { householdSchema, locationSchema, organizationSchema, useWorkspace, type Household, type Location } from '../lib/workspace'
import { ActionMessages, Alert, Badge, Empty, ErrorPanel, Field, Loading, PageHead } from '../components/ui'
import { formatDate } from '../lib/format'
import { AllowancePolicy } from '../components/VisitManagement'

const dashboardSchema = z.object({
  location: locationSchema, organization: organizationSchema,
  inventory: z.object({ availableUnits: z.number(), expiringBatches: z.number(), quarantinedBatches: z.number() }),
  donations: z.object({ pending: z.number(), needsReview: z.number() }), events: z.object({ upcoming: z.number() }),
  households: z.object({ pending: z.number() }),
  locations: z.array(z.object({ id: z.string(), name: z.string(), availableUnits: z.number(), pendingDonations: z.number(), upcomingEvents: z.number() })),
  recentActivity: z.array(z.unknown()),
})
export function Today() {
  const query = useQuery('/dashboard', dashboardSchema), context = useWorkspace()
  if (query.loading) return <Loading />
  if (query.error) return <ErrorPanel error={query.error} retry={query.reload} />
  const data = query.data
  if (!data) return <Empty title="No dashboard available" />
  const counts = [
    [data.donations.pending, 'Incoming offers', '/volunteer?tab=receive'],
    [data.inventory.expiringBatches, 'Food needing attention', '/volunteer?tab=inventory'],
    [data.donations.needsReview, 'Offers needing review', '/volunteer?tab=receive'],
    [data.events.upcoming, 'Upcoming distributions', '/volunteer?tab=events'],
    [data.inventory.quarantinedBatches, 'Batches on hold', '/volunteer?tab=inventory'],
    [data.households.pending, 'Households awaiting review', '/workspace?tab=households'],
  ] as const
  return <div className="stack-lg"><h2>Today at {data.location.name}</h2><div className="grid three">{counts.map(([count,label,to]) => <Link className="card decision-card" to={to} key={label}><strong className="stat">{count}</strong><span>{label} →</span></Link>)}</div>
    <div className="panel">{data.inventory.availableUnits} units available across different products. Unit counts are not weights or meal estimates.</div>
    {data.locations.length > 1 && <section className="card stack"><h3>Across your charity</h3>{data.locations.map(l => <div className="between" key={l.id}><div><strong>{l.name}</strong><p className="small muted">{l.availableUnits} available units · {l.pendingDonations} offers · {l.upcomingEvents} events</p></div><button className="btn secondary small" onClick={() => context.select(l.id)}>Open location</button></div>)}</section>}
  </div>
}
function LocationForm({ existing, onSaved }: { existing?: Location; onSaved: () => void }) {
  const action = useAction(), [form,setForm] = useState({ name: existing?.name || '', code: existing?.code || '', address: existing?.address || '', city: existing?.city || '', postalCode: existing?.postalCode || '', openingHours: existing?.openingHours || '', receivingInstructions: existing?.receivingInstructions || '', collectionAvailable: existing?.collectionAvailable || false, storageTypes: existing?.storageTypes || ['ambient'], active: existing?.active ?? true })
  async function submit(e: FormEvent) { e.preventDefault(); await action.run(async () => { await mutation(existing ? `/locations/${existing.id}` : '/locations', locationSchema, existing ? form : { ...form, active: undefined }, existing ? 'PATCH' : 'POST'); onSaved() }, 'Location saved.') }
  return <form className="card stack" onSubmit={submit}><h3>{existing ? `Manage ${existing.name}` : 'Add a location'}</h3><ActionMessages error={action.error} success={action.success}/><div className="form-grid">{(['name','code','address','city','postalCode','openingHours','receivingInstructions'] as const).map(field => <Field key={field} label={{name:'Location name',code:'Destination code',address:'Address',city:'Town / city',postalCode:'Postal code',openingHours:'Opening and receiving hours',receivingInstructions:'Receiving and collection instructions'}[field]} required={['name','code','address'].includes(field)}><input value={form[field]} required={['name','code','address'].includes(field)} onChange={e => setForm({...form,[field]:e.target.value})} maxLength={field === 'receivingInstructions' ? 2000 : 500}/></Field>)}</div><fieldset className="stack"><legend>Storage available</legend>{['ambient','chilled','frozen'].map(storage => <label className="check" key={storage}><input type="checkbox" checked={form.storageTypes.includes(storage)} onChange={e => setForm({...form,storageTypes:e.target.checked ? [...form.storageTypes,storage] : form.storageTypes.filter(s=>s!==storage)})}/>{storage}</label>)}</fieldset><label className="check"><input type="checkbox" checked={form.collectionAvailable} onChange={e=>setForm({...form,collectionAvailable:e.target.checked})}/>Collection from donors can be arranged</label>{existing && <label className="check"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Location active and visible to the public</label>}<button className="btn" disabled={action.pending || !form.storageTypes.length}>Save location</button></form>
}
function Locations() {
  const context = useWorkspace(), query = useQuery('/locations?all=true', z.array(locationSchema)), [edit,setEdit] = useState<string|null>(null)
  return <div className="stack"><div className="between"><h2>Locations</h2>{context.can('policy') && <button className="btn" onClick={()=>setEdit('new')}>Add location</button>}</div>{edit === 'new' && <LocationForm onSaved={()=>{setEdit(null);query.reload();context.reload()}}/>}{query.loading ? <Loading/> : query.error ? <ErrorPanel error={query.error} retry={query.reload}/> : query.data?.map(l=>edit===l.id ? <LocationForm key={l.id} existing={l} onSaved={()=>{setEdit(null);query.reload();context.reload()}}/> : <article className="card stack" key={l.id}><div className="between"><h3>{l.name}</h3><Badge status={l.active?'active':'paused'}/></div><p>{l.address} · {l.code}</p><p className="small muted">{l.openingHours} · {l.storageTypes.join(', ')}</p><p>{l.receivingInstructions}</p><div className="row"><button className="btn secondary small" onClick={()=>context.select(l.id)}>Use this location</button><button className="btn secondary small" onClick={()=>setEdit(l.id)}>Edit details</button></div></article>)}</div>
}
const invitationSchema = z.object({id:z.string(),email:z.string(),role:z.string(),expiresAt:z.string(),acceptedAt:z.string().nullable().optional()})
function People() {
  const context=useWorkspace(), query=useQuery('/staff',z.object({memberships:z.array(membershipSchema),invitations:z.array(invitationSchema)})), action=useAction()
  const [email,setEmail]=useState(''),[role,setRole]=useState('volunteer'),[locationId,setLocation]=useState(context.selectedId),[duties,setDuties]=useState<string[]>(['receive','checkin']),[revoke,setRevoke]=useState<string|null>(null)
  return <div className="stack-lg"><form className="card stack" onSubmit={e=>{e.preventDefault();void action.run(async()=>{await mutation('/staff/invitations',invitationSchema,{email,role,...(role!=='charity_manager'?{locationId}:{}),duties:role==='volunteer'?duties:[]});setEmail('');query.reload()},'Invitation created. The expiring activation link is in the recipient’s email or local outbox.')}}><h2>Invite a team member</h2><p className="muted small">An existing account gains this membership. Each person chooses their own password when activating a new account.</p><ActionMessages error={action.error} success={action.success}/><div className="form-grid"><Field label="Email" required><input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></Field><Field label="Membership role"><select value={role} onChange={e=>setRole(e.target.value)}><option value="volunteer">Volunteer</option>{context.can('policy') && <><option value="location_manager">Location manager</option><option value="charity_manager">Charity manager</option></>}</select></Field>{role!=='charity_manager' && <Field label="Assigned location"><select value={locationId} onChange={e=>setLocation(e.target.value)}>{context.locations.filter(l=>l.organizationId===context.location?.organizationId && (context.can('policy')||l.id===context.selectedId)).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></Field>}</div>{role==='volunteer' && <fieldset className="stack"><legend>Assigned duties</legend><div className="row">{['receive','inventory','events','checkin','delivery'].map(d=><label className="check" key={d}><input type="checkbox" checked={duties.includes(d)} onChange={e=>setDuties(e.target.checked?[...duties,d]:duties.filter(x=>x!==d))}/>{d}</label>)}</div></fieldset>}<button className="btn" disabled={action.pending}>Create invitation</button></form>
  {query.loading?<Loading/>:query.error?<ErrorPanel error={query.error} retry={query.reload}/>:<><h2>Current memberships</h2>{query.data?.memberships.map(m=><article key={m.id} className="card stack"><div className="between"><div><h3>{m.userName||m.email||'Team member'}</h3><p>{m.role.replaceAll('_',' ')} · {m.locationName||'All charity locations'}</p><p className="small muted">{m.duties.join(', ')}</p></div>{(context.can('policy')||m.role==='volunteer')&&<button className="btn danger small" onClick={()=>setRevoke(m.id)}>Remove access</button>}</div>{revoke===m.id&&<div className="panel warning stack"><p>Remove only this membership? The account and its memberships elsewhere remain active.</p><button className="btn danger" disabled={action.pending} onClick={()=>void action.run(async()=>{await mutation(`/staff/memberships/${m.id}`,okSchema,{},'DELETE');setRevoke(null);query.reload();context.reload()},'Membership removed.')}>Confirm access removal</button></div>}</article>)}<h2>Invitations</h2>{query.data?.invitations.length?query.data.invitations.map(i=><div className="card" key={i.id}>{i.email} · {i.role.replaceAll('_',' ')}<p className="small muted">{i.acceptedAt?'Activated':`Expires ${formatDate(i.expiresAt,undefined,true)}`}</p></div>):<Empty title="No pending invitations"/>}</>}</div>
}
function HouseholdForm({ household,onSaved }: {household?:Household;onSaved:()=>void}) {
  const action=useAction(),[label,setLabel]=useState(household?.label||''),[size,setSize]=useState(household?.approvedSize||1),[status,setStatus]=useState(household?.status||'approved'),[notes,setNotes]=useState(household?.notes||''),[collectors,setCollectors]=useState(household?.members.map(m=>m.id).join(', ')||'')
  return <form className="card stack" onSubmit={e=>{e.preventDefault();void action.run(async()=>{await mutation(household?`/households/${household.id}`:'/households',householdSchema,{label,approvedSize:size,status,notes,userIds:collectors.split(',').map(x=>x.trim()).filter(Boolean)},household?'PATCH':'POST');onSaved()},'Household saved.')}}><h3>{household?'Review household':'Create assisted household'}</h3><ActionMessages error={action.error} success={action.success}/><div className="form-grid"><Field label="Household reference / name" required><input required value={label} onChange={e=>setLabel(e.target.value)} maxLength={160}/></Field><Field label="Approved household size" required><input type="number" min={1} max={50} required value={size} onChange={e=>setSize(Number(e.target.value))}/></Field><Field label="Eligibility"><select value={status} onChange={e=>setStatus(e.target.value)}>{['pending','approved','paused'].map(s=><option key={s}>{s}</option>)}</select></Field><Field label="Authorized account IDs" hint="Comma-separated account IDs. Leave empty for phone or in-person collection; no smartphone is required."><input value={collectors} onChange={e=>setCollectors(e.target.value)}/></Field><Field label="Private eligibility notes"><textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={2000}/></Field></div><button className="btn" disabled={action.pending}>Save household</button></form>
}
function Households() {
  const query=useQuery('/households',z.array(householdSchema)),[edit,setEdit]=useState<string|null>(null)
  return <div className="stack"><div className="between"><h2>Household eligibility</h2><button className="btn" onClick={()=>setEdit('new')}>Add assisted household</button></div><p className="muted">Approval and allowances belong to this charity. Changes here do not change eligibility with other charities.</p>{edit==='new'&&<HouseholdForm onSaved={()=>{setEdit(null);query.reload()}}/>}{query.loading?<Loading/>:query.error?<ErrorPanel error={query.error} retry={query.reload}/>:query.data?.length?query.data.map(h=>edit===h.id?<HouseholdForm key={h.id} household={h} onSaved={()=>{setEdit(null);query.reload()}}/>:<article className="card stack" key={h.id}><div className="between"><h3>{h.label}</h3><Badge status={h.status}/></div><p>{h.approvedSize} approved household members · {h.members.map(m=>m.name).join(', ')||'Assisted collection without an online account'}</p><p className="small muted">{h.notes}</p><button className="btn secondary small" onClick={()=>setEdit(h.id)}>Review household</button></article>):<Empty title="No households enrolled"/>}</div>
}
export const sellerSchema=z.object({enabled:z.boolean(),mode:z.enum(['disabled','local-fixture']),destinationLabel:z.string(),currency:z.string()})
export function SellerSettings(){const query=useQuery('/seller-settings',sellerSchema);return query.loading?<Loading/>:query.error?<ErrorPanel error={query.error} retry={query.reload}/>:query.data?<SellerForm initial={query.data} reload={query.reload}/>:null}
function SellerForm({initial,reload}:{initial:z.infer<typeof sellerSchema>;reload:()=>void}){const action=useAction(),[form,setForm]=useState(initial);return <form className="card stack" onSubmit={e=>{e.preventDefault();void action.run(async()=>{await mutation('/seller-settings',sellerSchema,form,'PATCH');reload()},'Seller settings saved.')}}><h2>Charity sales settings</h2><ActionMessages error={action.error} success={action.success}/><Alert kind="info">Local payment simulation records test outcomes without moving money. Enabling sales does not publish stock; donor permissions, protected aid quantities and confirmed closeout still apply.</Alert><label className="check"><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/>Allow public surplus sales for this charity</label><div className="form-grid"><Field label="Payment mode"><select value={form.mode} onChange={e=>setForm({...form,mode:e.target.value as typeof form.mode})}><option value="disabled">Disabled</option><option value="local-fixture">Local simulation</option></select></Field><Field label="Payment destination label" required><input required value={form.destinationLabel} onChange={e=>setForm({...form,destinationLabel:e.target.value})}/></Field><Field label="Currency"><input value={form.currency} disabled/></Field></div><button className="btn" disabled={action.pending}>Save sales settings</button></form>}
function CharitySettings(){const context=useWorkspace(),action=useAction(),org=context.workspace?.organization;const [name,setName]=useState(org?.name||''),[email,setEmail]=useState(org?.supportEmail||''),[address,setAddress]=useState(org?.address||''),[privacy,setPrivacy]=useState(org?.privacyContact||'');return <div className="stack-lg"><form className="card stack" onSubmit={e=>{e.preventDefault();void action.run(async()=>{await mutation(`/organizations/${org?.id}`,organizationSchema,{name,supportEmail:email,address,privacyContact:privacy},'PATCH');context.reload()},'Charity information saved.')}}><h2>Charity information</h2><ActionMessages error={action.error} success={action.success}/><div className="form-grid"><Field label="Charity name" required><input value={name} required onChange={e=>setName(e.target.value)}/></Field><Field label="Support email"><input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></Field><Field label="Address"><input value={address} onChange={e=>setAddress(e.target.value)}/></Field><Field label="Privacy contact"><input type="email" value={privacy} onChange={e=>setPrivacy(e.target.value)}/></Field></div><button className="btn" disabled={action.pending}>Save charity information</button></form><AllowancePolicy/><SellerSettings/></div>}
export default function WorkspacePage(){const context=useWorkspace(),[params,setParams]=useSearchParams(),tab=params.get('tab')||'today';const tabs=[['today','Today','read'],['locations','Locations','manage'],['people','Team','people'],['households','Households','people'],['policy','Charity policy','policy']].filter(([, ,cap])=>context.can(cap));return <><PageHead eyebrow={context.workspace?.organization.name||'Team workspace'} title={context.location?.name||'Choose your workspace'} description="Manage the people, places and policies behind today's food sharing." action={<Link className="btn" to="/volunteer">Open operations</Link>}/><nav className="tabs" aria-label="Workspace sections">{tabs.map(([id,label])=><button key={id} className={`btn small ${tab===id?'':'secondary'}`} onClick={()=>setParams({tab:id})} aria-pressed={tab===id}>{label}</button>)}</nav>{!tabs.some(([id])=>id===tab)?<Alert kind="info">Your membership does not include this action at this location.</Alert>:tab==='locations'?<Locations/>:tab==='people'?<People/>:tab==='households'?<Households/>:tab==='policy'?<CharitySettings/>:<Today/>}</>}
